const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

const ADD_OBJECT = 'ADD_OBJECT';
const EDIT_OBJECT = 'EDIT_OBJECT';
const REMOVE_OBJECT = 'REMOVE_OBJECT';
const LOAD_OBJECTS = 'LOAD_OBJECTS';

export {
  ADD_NOTIFICATION,
  REMOVE_NOTIFICATION,
  ADD_OBJECT,
  EDIT_OBJECT,
  REMOVE_OBJECT,
  LOAD_OBJECTS
};
